name: mlflow-examples-sklearn
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow>=1.17.0
    - scikit-learn==0.24.2
    - matplotlib==3.2.1
    - pyarrow>=1.0.0
    - onnx==1.10.1
    - onnxmltools==1.9.1
    - onnxruntime==1.8.1
    - pyspark==3.2.0
    - pytest
