name: mlflow-examples-keras_tf_wine
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow>=1.17.0
    - tensorflow==2.3.0
    - tensorflowjs
    - scikit-learn==0.24.2
    - onnx==1.9.0
    - onnxmltools==1.7.0
    - onnxruntime==1.7.0 
    - keras2onnx==1.7.0
