params:
  epochs: 30
  batch_size: 32
  num_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000


artifacts:

  artifacts_dir: artifacts
  summary_dir : summary
  model_dir: model
  plots_dir: plots
  checkpoint_dir: checkpoints
  model_name: model.h5
  plot_name: plot.png
  summary_name: model_summary.txt

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs
  log_name: app.log
  tensorboard_logs_name: tensorboard_log

  
# we can use Json also intead of yaml
# How to check in python envoriment
#import yaml
#from src.utils.common  import read_config
# read_config("config.yaml") 
# we will get like dict
# It will call common.py internally if we call read_config