version: '3.0'
services:
  mlflow:
    build:
      dockerfile: Dockerfile-mlflow-s3
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
