params:
  epochs: 1000
  batch_size: 128
  loss_function: mse
  metrics: mae
  optimizer: RMSprop
  #learning_rate: 0.001
  validation_datasize: 5000
  test_size_value: 0.2
  random_state: 42


artifacts:

  artifacts_dir: artifacts
  summary_dir : summary
  model_dir: model
  plots_dir: plots
  checkpoint_dir: checkpoints
  model_name: model.h5
  plot_name: plot.png
  summary_name: model_summary.txt
  ckpt_name: model_ckpt.h5 

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs
  log_name: app.log
  tensorboard_logs_name: tensorboard_log

  
