name: mlflow-examples-e2e-ml-pipeline
channels:
  - conda-forge
dependencies:
  - python=3.7.6
  - pip:
    - mlflow>=1.10.0
    - scikit-learn==0.24.2
    - pytest
    - pytest-ordering
    - psutil
