name: mlflow-examples-onnx
channels:
  - defaults
dependencies:
  - python=3.7.56
  - pip:
    - mlflow>=1.17.0
    - onnx==1.6.0
    - onnxruntime==1.1.0
    - onnxmltools==1.6.0
    - skl2onnx==1.6.0
